spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: university-service
          uri: lb://university-service
          predicates:
            - Path=/university-service/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8900
#debug: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/