
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tahirakhan/vroozi-cloud-config-repo
          username: tahirakhan
          password: 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
          default-label: master
  application:
    name:config-server
server:
  port: ${port:8888}
