
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tahirakhan/vroozi-cloud-config-repo
          username: tahirakhan
          password: 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
          default-label: master
  application:
    name:config-server
server:
  port: ${port:8888}
