spring:
  application:
    name: university-service
  cloud:
    config:
      uri: http://localhost:8888
  main:
    allow-bean-definition-overriding: true

server:
  port: 8101

management:
  metrics:
    export:
      datadog:
        enabled: false
      prometheus:
        enabled: true
      jmx:
        enabled: true
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka