spring:
  application:
    name: university-service
  cloud:
    config:
      uri: http://localhost:8888
  main:
    allow-bean-definition-overriding: true

server:
  port: 8101

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "refresh"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka