spring:
  application:
    name: university-service
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8101

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "refresh"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}