spring:
  application:
    name: university-service
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8101

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "refresh"

#student-service:
#  ribbon:
#    listOfServers: http://localhost:8001, http://localhost:8002